import type { Meta, StoryObj } from '@storybook/react';
import { NextIntlClientProvider } from 'next-intl';
import messages from '../messages/en.json';
import Breadcrumbs, { BreadcrumbsCompact } from '../src/components/Breadcrumbs';

/**
 * Breadcrumbs auto-generates a trail from the current URL path, or accepts
 * a custom `items` array to override it.
 *
 * The `parameters.nextjs.navigation.pathname` key is used by
 * `@storybook/nextjs` to mock `next/navigation.usePathname`, which
 * `next-intl` delegates to internally.
 */

const withI18n = (Story: React.ComponentType) => (
  <NextIntlClientProvider locale="en" messages={messages}>
    <Story />
  </NextIntlClientProvider>
);

const meta: Meta<typeof Breadcrumbs> = {
  title: 'Components/Breadcrumbs',
  component: Breadcrumbs,
  tags: ['autodocs'],
  parameters: {
    layout: 'fullscreen',
    nextjs: {
      navigation: { pathname: '/category/bitcoin' },
    },
  },
  decorators: [withI18n],
  argTypes: {
    showHomeIcon: { control: 'boolean' },
    className: { control: 'text' },
  },
};

export default meta;
type Story = StoryObj<typeof meta>;

/** Provides explicit items — bypasses the auto-generation from pathname. */
export const WithCustomItems: Story = {
  args: {
    items: [
      { label: 'Home', href: '/' },
      { label: 'Category', href: '/category' },
      { label: 'Bitcoin', href: '/category/bitcoin' },
    ],
    showHomeIcon: true,
  },
  parameters: {
    nextjs: { navigation: { pathname: '/category/bitcoin' } },
  },
};

/** Deep path with 4 levels. */
export const DeepPath: Story = {
  args: {
    items: [
      { label: 'Home', href: '/' },
      { label: 'Markets', href: '/markets' },
      { label: 'Coins', href: '/markets/coins' },
      { label: 'Ethereum', href: '/markets/coins/ethereum' },
    ],
  },
  parameters: {
    nextjs: { navigation: { pathname: '/markets/coins/ethereum' } },
  },
};

/** Auto-generated from a two-segment path. */
export const AutoGenerated: Story = {
  parameters: {
    nextjs: { navigation: { pathname: '/category/defi' } },
  },
};

/** Without the home icon. */
export const NoHomeIcon: Story = {
  args: {
    items: [
      { label: 'Home', href: '/' },
      { label: 'Search', href: '/search' },
      { label: 'Results', href: '/search/bitcoin' },
    ],
    showHomeIcon: false,
  },
  parameters: {
    nextjs: { navigation: { pathname: '/search/bitcoin' } },
  },
};

/** Compact back-navigation variant (for mobile). */
export const Compact: Story = {
  render: (args) => (
    <NextIntlClientProvider locale="en" messages={messages}>
      <BreadcrumbsCompact className={args.className} />
    </NextIntlClientProvider>
  ),
  parameters: {
    nextjs: { navigation: { pathname: '/category/defi' } },
  },
};

export const DarkBackground: Story = {
  ...WithCustomItems,
  parameters: {
    ...WithCustomItems.parameters,
    backgrounds: { default: 'dark' },
  },
};
